[dependencies]
base = "0.7.4"
matchers = "https://github.com/kritzcreek/motoko-matchers#7f95f69ae9a399cedf161d90738db822f315c07e"
uuid = "https://github.com/aviate-labs/uuid.mo#v0.2.0"
array = "https://github.com/aviate-labs/array.mo#v0.2.0"